export const FIB = [1, 2, 3, 5, 8, 13, 21, 34];

export const FIB_LABELS = {
  en: {
    1: 'Very Low',
    2: 'Low',
    3: 'Moderate',
    5: 'Good',
    8: 'Strong',
    13: 'Very Strong',
    21: 'Excellent',
    34: 'Outstanding',
  },
  zh: {
    1: '極低',
    2: '低',
    3: '普通',
    5: '良好',
    8: '強',
    13: '很強',
    21: '優秀',
    34: '卓越',
  },
};

export const COLORS = [
  '#00d4ff',
  '#22d3ee',
  '#34d399',
  '#4ade80',
  '#facc15',
  '#fb923c',
  '#f87171',
  '#c084fc',
];

export const AVATAR_COLORS = [
  '#7c3aed',
  '#0891b2',
  '#059669',
  '#d97706',
  '#dc2626',
  '#db2777',
  '#4f46e5',
  '#0d9488',
];

export const I18N = {
  en: {
    app_title: 'Fibonacci Voting Game',
    app_sub: 'Fibonacci Scoring System v2.0',
    tab_setup: 'Setup',
    tab_vote: 'Vote',
    tab_results: 'Results',
    tab_admin: 'Admin',
    setup_instr_title: 'Game Configuration',
    setup_instr_body:
      'Configure participants, voting options, and game mode. Fibonacci values reflect strength of preference.',
    setup_instr_zh:
      'Please rate each option using Fibonacci values (1–34). Higher numbers indicate greater value.',
    participants_title: 'Participants',
    add_participant: 'Add Participant',
    participant_placeholder: 'Enter name…',
    add: 'Add',
    add_anon: '+ Anonymous',
    clear_all: 'Clear All',
    voting_options_title: 'Voting Options',
    add_option: '+ Add Option',
    game_mode_title: 'Game Mode',
    mode_a_name: 'Mode A',
    mode_a_desc: 'Pick One',
    mode_b_name: 'Mode B',
    mode_b_desc: 'Rate All',
    mode_c_name: 'Mode C',
    mode_c_desc: 'Budget 34',
    settings_title: 'Settings',
    anonymous_voting: 'Anonymous Voting',
    timer_enable: 'Enable Timer',
    timer_seconds: 'Timer (seconds)',
    show_live: 'Show Live Results',
    fib_ref_title: 'Fibonacci Reference',
    load_sample: '📦 Load Sample Data',
    start_game: '🚀 Start Game',
    select_voter_title: 'Select Your Name to Vote',
    select_voter_desc: 'Choose your name from the list, then cast your votes below.',
    select_voter_prompt: 'Select your name above to begin voting',
    time_remaining: 'Time Remaining',
    timer_desc: 'Vote before the timer expires!',
    pause: 'Pause',
    resume: 'Resume',
    reset_timer: 'Reset',
    budget_left: 'pts remaining',
    clear_votes: '🗑️ Clear My Votes',
    submit_votes: '✓ Submit Votes',
    no_votes_yet: 'No votes yet. Start the game and vote to see results!',
    ranking_title: 'Ranking',
    chart_title: 'SCORE DISTRIBUTION',
    vote_detail: 'Vote Detail',
    export_title: 'Export Results',
    csv_desc: 'Spreadsheet format',
    report_label: 'Text Report',
    report_desc: 'Summary report',
    admin_controls: 'Admin Controls',
    reset_all: '🔄 Reset All Votes',
    back_setup: '← Back to Setup',
    reveal_results: '👁️ Reveal Results',
    vote_log: 'Vote Log',
    confirm_reset_title: '⚠️ Reset All Votes?',
    confirm_reset_body:
      'This will clear all submitted votes. This action cannot be undone.',
    cancel: 'Cancel',
    confirm_reset: 'Yes, Reset',
    toast_added: 'Participant added!',
    toast_exists: 'Name already exists.',
    toast_game_start: 'Game started! Switch to Vote tab.',
    toast_submitted: 'Votes submitted!',
    toast_reset: 'All votes reset.',
    toast_no_votes: 'Please cast at least one vote.',
    toast_budget_over: 'Budget exceeded! You only have 34 points.',
    toast_already_submitted: 'You have already submitted. Edit your votes first.',
    toast_pick_one: 'Pick One mode: select only 1 option.',
    stat_voters: 'Total Voters',
    stat_options: 'Options',
    stat_votes: 'Total Votes',
    stat_top: 'Top Score',
    mode_label_A: 'Preference Vote (Pick One)',
    mode_label_B: 'Value Scoring (Rate All)',
    mode_label_C: 'Strategic Investment (Budget 34)',
    winner: '🏆 Winner',
    voted_badge: 'Voted',
    waiting_badge: 'Waiting',
    your_vote: 'Your vote:',
    no_vote: 'Not voted',
    median: 'Median',
    mean: 'Mean',
    total: 'Total',
    votes_count: 'Votes',
    ai_generate_options: '🤖 AI Generate Options',
    ai_refine_options: '🤖 AI Refine Descriptions',
    ai_summary_report: '🤖 AI Summary Report',
    ai_generating: 'Generating...',
    ai_prompt_placeholder: 'Describe the topic (e.g., "New company logo designs")',
  },
  zh: {
    app_title: '費波那契投票遊戲',
    app_sub: '費波那契評分系統 v2.0',
    tab_setup: '設定',
    tab_vote: '投票',
    tab_results: '結果',
    tab_admin: '管理',
    setup_instr_title: '遊戲設定',
    setup_instr_body: '設定參與者、投票選項與遊戲模式。費波那契數值反映偏好強度。',
    setup_instr_zh: '請根據您的判斷，使用費波那契數列（1–34）為各方案評分，數字越高代表價值越高。',
    participants_title: '參與者',
    add_participant: '新增參與者',
    participant_placeholder: '輸入姓名…',
    add: '新增',
    add_anon: '+ 匿名',
    clear_all: '清除全部',
    voting_options_title: '投票選項',
    add_option: '+ 新增選項',
    game_mode_title: '遊戲模式',
    mode_a_name: '模式 A',
    mode_a_desc: '選一項',
    mode_b_name: '模式 B',
    mode_b_desc: '全部評分',
    mode_c_name: '模式 C',
    mode_c_desc: '預算 34',
    settings_title: '設定',
    anonymous_voting: '匿名投票',
    timer_enable: '開啟計時',
    timer_seconds: '計時（秒）',
    show_live: '即時顯示結果',
    fib_ref_title: '費波那契參考',
    load_sample: '📦 載入範例資料',
    start_game: '🚀 開始遊戲',
    select_voter_title: '選擇您的姓名開始投票',
    select_voter_desc: '從列表中選擇姓名，然後在下方投票。',
    select_voter_prompt: '請在上方選擇您的姓名',
    time_remaining: '剩餘時間',
    timer_desc: '計時結束前請完成投票！',
    pause: '暫停',
    resume: '繼續',
    reset_timer: '重設',
    budget_left: '點數剩餘',
    clear_votes: '🗑️ 清除投票',
    submit_votes: '✓ 提交投票',
    no_votes_yet: '尚無投票。開始遊戲並投票以查看結果！',
    ranking_title: '排名',
    chart_title: '分數分布',
    vote_detail: '詳細投票結果',
    export_title: '匯出結果',
    csv_desc: '試算表格式',
    report_label: '文字報告',
    report_desc: '摘要報告',
    admin_controls: '管理員控制',
    reset_all: '🔄 重設所有投票',
    back_setup: '← 返回設定',
    reveal_results: '👁️ 顯示結果',
    vote_log: '投票記錄',
    confirm_reset_title: '⚠️ 重設所有投票？',
    confirm_reset_body: '這將清除所有已提交的投票，此操作無法復原。',
    cancel: '取消',
    confirm_reset: '確認重設',
    toast_added: '參與者已新增！',
    toast_exists: '姓名已存在。',
    toast_game_start: '遊戲已開始！請切換至投票頁籤。',
    toast_submitted: '投票已提交！',
    toast_reset: '所有投票已重設。',
    toast_no_votes: '請至少投一票。',
    toast_budget_over: '超出預算！您只有 34 點。',
    toast_already_submitted: '您已提交。如需修改請先清除。',
    toast_pick_one: '選一項模式：只能選擇 1 個選項。',
    stat_voters: '總投票人數',
    stat_options: '選項數',
    stat_votes: '總票數',
    stat_top: '最高分',
    mode_label_A: '偏好投票（選一項）',
    mode_label_B: '價值評分（全部評分）',
    mode_label_C: '策略投資（預算34）',
    winner: '🏆 冠軍',
    voted_badge: '已投票',
    waiting_badge: '等待中',
    your_vote: '您的評分：',
    no_vote: '未投票',
    median: '中位數',
    mean: '平均',
    total: '總分',
    votes_count: '票數',
    ai_generate_options: '🤖 AI 生成選項',
    ai_refine_options: '🤖 AI 優化說明',
    ai_summary_report: '🤖 AI 總結報告',
    ai_generating: '生成中...',
    ai_prompt_placeholder: '描述主題 (例如: "新公司標誌設計")',
  },
};
